name: Deploy to Brazil testing
on:
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and deploy to Brazil testing
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: https://brazil-testing.curseofmirra.com/board

    steps:
      - uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:server

      - name: Create ssh private key file from env var
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ vars.TS_BRAZIL_HOST }}
        run: |
          set -ex
          mkdir -p ~/.ssh/
          sed -E 's/(-+(BEGIN|END) OPENSSH PRIVATE KEY-+) *| +/\1\n/g' <<< "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          ssh-keyscan $HOST >> ~/.ssh/known_hosts

      - name: Copy deploy script
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ vars.TS_BRAZIL_HOST }}
        run: |
          set -ex 
          rsync -avz --mkpath deploy.sh ${SSH_USERNAME}@${SSH_HOST}:/home/${SSH_USERNAME}/deploy-script/

      - name: Execute deploy script
        env:
          SSH_HOST: ${{ vars.TS_BRAZIL_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          MIX_ENV: ${{ vars.MIX_ENV }}
          PHX_SERVER: ${{ vars.PHX_SERVER }}
          PHX_HOST: ${{ vars.BRAZIL_HOST }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEWRELIC_APP_NAME: ${{ vars.NEWRELIC_APP_NAME_BRAZIL }}
          NEWRELIC_KEY: ${{ secrets.NEWRELIC_KEY }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          set -ex
          ssh ${SSH_USERNAME}@${SSH_HOST} \
                BRANCH_NAME=${BRANCH_NAME} \
                MIX_ENV=${MIX_ENV} \
                PHX_SERVER=${PHX_SERVER} \
                PHX_HOST=${PHX_HOST} \
                SECRET_KEY_BASE=${SECRET_KEY_BASE} \
                DATABASE_URL=${DATABASE_URL} \
                NEWRELIC_APP_NAME=${NEWRELIC_APP_NAME} \
                NEWRELIC_KEY=${NEWRELIC_KEY} \
                /home/${SSH_USERNAME}/deploy-script/deploy.sh
